spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          issuer-uri: http://localhost:9090/realms/el-aparato-simon-pintos
  application:
    name: springboot-keycloak
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    password: pass123
    username: root
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/elaparato?serverTimezone=UTC
jwt:
  auth:
    converter:
      principal-attribute: preferred_username
      resource-id: api-gateway-client
logging:
  level:
    org:
      springframework:
        security: DEBUG
server:
  servlet:
    context-path: /api

dh:
  keycloak:
    serverUrl: http://localhost:9090
    realm: el-aparato-simon-pintos
    clientId: api-internal-users-client
    clientSecret: 55hsPGIklyPmqv5olyraSsxCGA1aKwA8
    # El client secret no se expone, pero como no es un proyecto importante/público, así lo dejé
