server:
  port: 8181

spring:
  application:
    name: keycloak-admin

dh:
  keycloak:
    serverUrl: http://localhost:9090
    realm: gestion-usuarios
    clientId: api-internal-users-client
    clientSecret: r9kjki2527WL8TyPKNtk2ZjTSjBkzkEv
